disabled_rules:
  - line_length
  - force_cast
  - variable_name
  - nesting
  - type_name
included:
  - Revert/Sources
  - Revert-tvOS/Sources
  - Shared/Sources

generic_type_name:
  max_length:
    warning: 32
    error: 1000
